name: Broken Links Checker
on:
 push:
    branches:
      - main # Modify if you use a different main branch name, such as the legacy "master" name.
 pull_request:
    branches:
      - main # Modify if you use a different main branch name, such as the legacy "master" name.
      
env:
  WEBSITE_URL: "https://haystack.deepset.ai"
  ISSUE_TEMPLATE: ".github/workflows/check-broken-links.md"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Run Broken Links Checker
      run: npx broken-link-checker $WEBSITE_URL --ordered --recursive

    - uses: actions/checkout@v2
      if: failure()

    - uses: JasonEtco/create-an-issue@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: ${{ env.ISSUE_TEMPLATE }}
      if: failure()
